### ISSUE TITLE
Website Updates Mega List

### ISSUE THREAD

**Issue by ninadicara** [very-good-science/data-hazards#191]
There are lots of outstanding updates to the website needed. I'm going to list them all here and try to get them done alongside revising the Data Hazards 1.0 paper for re-submission. 

# Software Updates
- [x]  #158 Update to Sphinx Design - which I hope will also address #135
- [x] Update Python version to at least 3.9
- [x] Update GitHub actions to reflect new Python version

# Structure Updates
- [ ] Consider moving website to a `docs` folder and making the ontology file the main document in the repo home. Technically if these are the core hazards then that is what we are versioning.
- [x] #132 - Remove content folder.  Nat did this on the Data Ethics Club Website so should be okay and better to do sooner than later.
- [x] rename the `data-hazards` > `labels`
- [x] Move the Change Log as a subpage of the labels page
- [x] Add page with suggested new labels
- [x] Rename 'Contributing' > 'Contribute'
- [x] On Labels Page, re-introduce LHS menu (for change log, future suggestions, printable lables, ontology file)

# Content Updates
- [x] Make sure all the contributors from #131 are credited?
- [x] Change the colours on the Data Hazard labels with Sphinx Design - and alt-text options.
- [ ] Integrate feedback from previous issues into the repo #178 
- [x] Add new suggested labels to the suggested new labels page #151, #149, email in project inbox
- [x] Add info about the suggested labels page to the Contributing information
- [ ] Add an OSF pre-registration template to an OSF project for this and link to self-assessment - #76 
- [ ] #187 
- [ ] #188 - Look into where Nat got to with the Ontology file and potentially add it to the DH labels page with this update.
- [ ] Can I get Gareth's app working?? #56 
- [ ] See if I can make a contact form for submitting ideas etc without using Issues (not everyone has GitHub).
- [ ] Introduce a page for project owners about what doing a workshop involves?
- [ ] Review the workshop content - could it be better?

# Other
- [ ] YouTube - rename the videos? #170 
- [ ] Many moons ago, we made a Zenodo page to host all our talks, inspired by how the Turing Way folks do it. This needs updating big time. - Perhaps could link with a re-organisation of the 'Events' page.

**Comment by ninadicara** [comment]
Most of these are completed, and those that are not exist as separate issues. 
The only thing worth thinking about is probably adding an events/news bulletin section.
