### ISSUE TITLE
Credit for people who help with the project

### ISSUE THREAD

**Issue by ninadicara** [very-good-science/data-hazards#22]
In the spirit of all-contributors, it would be cool if on the website and repository we can credit people for their involvement in the project. e.g. peer review, feedback, ideas - would link in nicely too if we'd like people to be able to suggest changes to the hazards via GH issues. 

-----
### To-do:
- [x] Add all-contributors page to the website
- [x] Make sure all-contributors is up to date #36 
- [ ] Look at workshop 1 feedback and decide if we want to make any tweaks for workshop 2 about asking about credit

**Comment by NatalieThurlby** [comment]
@ninadicara: maybe we need to think about what specific to-do items there are on this issue at our next meeting

**Comment by NatalieThurlby** [comment]
I am thinking that we will probably not get very specific answers about this out of the initial workshop, because we don't ask very specific questions in the survey. Maybe we can see if any ideas about credit come to the fore when we ask people in the free text section of the feedback for this first workshop. If not, maybe in the future, we can ask more about specifics, e.g. would being credited in the acknowledgements section of data science papers make you more likely to participate? Would being credited as an author on a Data Hazards paper make you more likely to contribute?

**Comment by ninadicara** [comment]
Closing this for now because we've landed on all-contributors for credit :)
