### ISSUE TITLE
Tasks for seedcorn planning

### ISSUE THREAD

**Issue by NatalieZelenka** [very-good-science/data-hazards#59]
## To-do
- [x] Meet with Patty/Lily/Chiara (depending on who's organising) to decide how Data Hazards will feature in the seedcorn 
    - what format they'd like to do it (e.g. self-assessed by applicants web form)
    - when that needs doing by
-  ~~Design a survey for applicants to go out in the acception/rejection emails asking for their thoughts on the Data Hazards ethics part of the process. Presumably this will require us to update our ethics application.~~
- [x] Write the form
  - [x] Ask successful applicants if they'd be willing to complete the Data Hazards process (tickbox)
  - [x] decide: asynchronous process OR workshop (decided: asynchronous )
- [x] Add page to the website, explaining the seed corn trial
    - [x] Add Contents:
        - The purpose of applying data hazards
        - Which types of projects are relevant to apply hazards to
        - What the process will look like for them
            - Only inviting successful projects this time
        - Links to more context about the project
        - To contact me if they have any questions 
        - The purpose of this trial
            - So, far, researchers have found the process to be useful, and we think it will be for you, too.
            - They'll have an opportunity to feedback 
            - It won't affect their application if they choose not to take part
    - [ ] Update link from the timeline to the new materials
    - [ ] Get Lily to mirror the page on the JGI website as that will be a more official link for the applicants
- [ ] Design the asynchronous materials #77
- [ ] Write email text for successful/unsuccessful applicants
- [ ] Update survey for asynchronous materials
- [ ] Update Eng faculty ethics materials for asynchronous/seed corn process
--- 

## Form materials

>  ### Conditions for funding
>  We strongly encourage all participants to consider the ethical and societal implications of their work. Successful projects will have the opportunity to take part in a short, guided Data Hazards self-assessment for ethics in data science to assist with this.  You can read about the Data Hazards project [here](https://very-good-science.github.io/data-hazards/). 
>
> ### Application form
>  If successful, would you take part in a Data Hazards guided ethics self-assessment exercise? This is relevant to any project that involves statistics, AI, ML, algorithms, or data collection. 
> YES / NO
